version: 2
jobs:
  build:
    docker:
      - image: wecs/circle-ci-gcloud-node:0.1.0
    working_directory: ~/workspace
    environment:
      DEPLOYMENT_NAME: ci-cd
      PROJECT_ID: web-ci-cd
      CLUSTER_NAME: ci-cd
      CLUSTER_NAME_STAG: ci-cd-stag
      CLOUDSDK_COMPUTE_ZONE: us-west1-a	
      CONTAINER_NAME: ci-cd
      IMAGE: ci-cd
      REG_ID: ci-cd
      REG_ID_PROD: ci-cd-prod
      IMG_TAG: 0.1.0
      PROJECT_NAME: ci-cd
      DEPLOYMENT_ENVIRONMENT: staging
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install node packages
          command: |
                  #npm install
            cd /usr/local tar --strip-components 1 -xzf ~/workspace/bin/node-v8.2.1-linux-x64.tar.gz
            which node
            node -v
            apt-get -y update
            apt-get install -y default-jre
            apt-get install -y default-jdk
            add-apt-repository ppa:webupd8team/java
            apt-get update
            apt-get install oracle-java8-installer
            gedit ~/.bashrc
            export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
            export PATH=${PATH}:${JAVA_HOME}/bin
            echo $JAVA_HOME
            echo $PATH
      - run:
          name: Start app
          command: |
            npm start &
      - run:
          name: Run tests
          command: |
            npm test
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run:
          name: Build and Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./deployment.sh
            fi
